sudo: required

services:
  - docker

before_install:
  - docker build -t prahalladkb/docker-react -f Dockerfile.dev .

script:
 - docker run prahalladkb/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-068554231560"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
